// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DVG_FilmesWeb.Model
{
    [Table("TBClientes")]
    public partial class Tbclientes
    {
        public Tbclientes()
        {
            Tblocados = new HashSet<Tblocados>();
        }

        [Key]
        [StringLength(14)]
        [Unicode(false)]
        public string Documento { get; set; }
        [Required]
        [StringLength(60)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string Telefone { get; set; }
        [Required]
        [StringLength(60)]
        [Unicode(false)]
        public string Email { get; set; }

        [InverseProperty("DocClienteNavigation")]
        public virtual ICollection<Tblocados> Tblocados { get; set; }
    }
}