// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;


namespace DVG_FilmesWeb.Model
{
    [Table("TBCliente")]
    public partial class Tbcliente
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "O CPF deve conter 11 caracteres")]
        [Column("CPF")]
        [StringLength(60)]
        [Unicode(false)]
        [Display(Name ="CPF")]
        public string Cpf { get; set; }
        [Required(ErrorMessage = "Informe o Nome")]
        [StringLength(60)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Required(ErrorMessage = "Informe o Telefone")]
        [StringLength(20)]
        [Unicode(false)]
        public string Telefone { get; set; }
        [Required(ErrorMessage = "Informe o Email")]
        [StringLength(60)]
        [Unicode(false)]
        public string Email { get; set; }
    }
}