// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DVG_FilmesWeb.Model
{
    [Table("TBFilmes")]
    public partial class Tbfilmes
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Categoria")]
        public int IdCategoria { get; set; }
        [Required(ErrorMessage = "Informe o Nome")]
        [StringLength(50)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Required(ErrorMessage = "Informe a Descrição")]
        [StringLength(200)]
        [Unicode(false)]

        public string Descrição { get; set; }
        [Required(ErrorMessage = "Informe o Preço")]
        [Display(Name ="Preço")]
        public double Preco { get; set; }
        
        [ForeignKey("IdCategoria")]
        [InverseProperty("Tbfilmes")]
        [Display(Name = "Categoria")]
        public virtual Tbcategorias IdCategoriaNavigation { get; set; }
    }
}