// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DVG_FilmesWeb.Model
{
    public partial class VIDEO_LOCADORAContext : DbContext
    {
        public VIDEO_LOCADORAContext()
        {
        }

        public VIDEO_LOCADORAContext(DbContextOptions<VIDEO_LOCADORAContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Tbcategorias> Tbcategorias { get; set; }
        public virtual DbSet<Tbcliente> Tbcliente { get; set; }
        public virtual DbSet<Tbclientes> Tbclientes { get; set; }
        public virtual DbSet<Tbfilmes> Tbfilmes { get; set; }
        public virtual DbSet<Tblocados> Tblocados { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-8CJKJRB\\MAORIEXPRESS;Initial Catalog=VIDEO_LOCADORA;Persist Security Info=True;User ID=sa;Password=sa");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Tbclientes>(entity =>
            {
                entity.HasKey(e => e.Documento)
                    .HasName("PK__TBClient__AF73706CE31CA633");
            });

            modelBuilder.Entity<Tbfilmes>(entity =>
            {
                entity.HasOne(d => d.IdCategoriaNavigation)
                    .WithMany(p => p.Tbfilmes)
                    .HasForeignKey(d => d.IdCategoria)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__TBFilmes__IdCate__2C3393D0");
            });

            modelBuilder.Entity<Tblocados>(entity =>
            {
                entity.HasOne(d => d.DocClienteNavigation)
                    .WithMany(p => p.Tblocados)
                    .HasForeignKey(d => d.DocCliente)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__TBLocados__DocCl__276EDEB3");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}